name: Generate 3D Contribution City

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  iso_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: profile-3d-contrib/iso_calendar.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: AtharvPat
          template: classic
          base: ""
          config_timezone: America/Chicago
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
