name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  iso_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calendar.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: AtharvPat
          template: classic
          base: ""
          config_timezone: America/Chicago
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: stats.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: AtharvPat
          template: classic
          base: account, repositories
          config_timezone: America/Chicago
          plugin_stars: yes
          plugin_stars_limit: 0
          plugin_repositories: yes
          plugin_repositories_order: stars
          config_display: large
